name: Deploy via repository_dispatch
on: repository_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod-selfreview-test
    steps:
      - run: echo "deployed via repository_dispatch"
